name: IMAGEWORX
favicon: null
layout_spectrum: 0.3171
typography_spectrum: 0.58377
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 1
  lightness: 0.027977014891803265
  saturation: 0.5587583428714424
  rhythmicContrast: 0.20417717145755887
purpose: []
